// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AnalysisProcessor is an autogenerated mock type for the AnalysisProcessor type
type AnalysisProcessor struct {
	mock.Mock
}

type AnalysisProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalysisProcessor) EXPECT() *AnalysisProcessor_Expecter {
	return &AnalysisProcessor_Expecter{mock: &_m.Mock}
}

// MarkAnalyzeCallFailed provides a mock function with given fields: ctx, callID, cause
func (_m *AnalysisProcessor) MarkAnalyzeCallFailed(ctx context.Context, callID uuid.UUID, cause error) error {
	ret := _m.Called(ctx, callID, cause)

	if len(ret) == 0 {
		panic("no return value specified for MarkAnalyzeCallFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, error) error); ok {
		r0 = rf(ctx, callID, cause)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnalysisProcessor_MarkAnalyzeCallFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAnalyzeCallFailed'
type AnalysisProcessor_MarkAnalyzeCallFailed_Call struct {
	*mock.Call
}

// MarkAnalyzeCallFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - callID uuid.UUID
//   - cause error
func (_e *AnalysisProcessor_Expecter) MarkAnalyzeCallFailed(ctx interface{}, callID interface{}, cause interface{}) *AnalysisProcessor_MarkAnalyzeCallFailed_Call {
	return &AnalysisProcessor_MarkAnalyzeCallFailed_Call{Call: _e.mock.On("MarkAnalyzeCallFailed", ctx, callID, cause)}
}

func (_c *AnalysisProcessor_MarkAnalyzeCallFailed_Call) Run(run func(ctx context.Context, callID uuid.UUID, cause error)) *AnalysisProcessor_MarkAnalyzeCallFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(error))
	})
	return _c
}

func (_c *AnalysisProcessor_MarkAnalyzeCallFailed_Call) Return(_a0 error) *AnalysisProcessor_MarkAnalyzeCallFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnalysisProcessor_MarkAnalyzeCallFailed_Call) RunAndReturn(run func(context.Context, uuid.UUID, error) error) *AnalysisProcessor_MarkAnalyzeCallFailed_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessAnalyzeCall provides a mock function with given fields: ctx, callID
func (_m *AnalysisProcessor) ProcessAnalyzeCall(ctx context.Context, callID uuid.UUID) error {
	ret := _m.Called(ctx, callID)

	if len(ret) == 0 {
		panic("no return value specified for ProcessAnalyzeCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, callID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AnalysisProcessor_ProcessAnalyzeCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessAnalyzeCall'
type AnalysisProcessor_ProcessAnalyzeCall_Call struct {
	*mock.Call
}

// ProcessAnalyzeCall is a helper method to define mock.On call
//   - ctx context.Context
//   - callID uuid.UUID
func (_e *AnalysisProcessor_Expecter) ProcessAnalyzeCall(ctx interface{}, callID interface{}) *AnalysisProcessor_ProcessAnalyzeCall_Call {
	return &AnalysisProcessor_ProcessAnalyzeCall_Call{Call: _e.mock.On("ProcessAnalyzeCall", ctx, callID)}
}

func (_c *AnalysisProcessor_ProcessAnalyzeCall_Call) Run(run func(ctx context.Context, callID uuid.UUID)) *AnalysisProcessor_ProcessAnalyzeCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AnalysisProcessor_ProcessAnalyzeCall_Call) Return(_a0 error) *AnalysisProcessor_ProcessAnalyzeCall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AnalysisProcessor_ProcessAnalyzeCall_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *AnalysisProcessor_ProcessAnalyzeCall_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalysisProcessor creates a new instance of AnalysisProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalysisProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalysisProcessor {
	mock := &AnalysisProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
