// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AvatarStorage is an autogenerated mock type for the AvatarStorage type
type AvatarStorage struct {
	mock.Mock
}

type AvatarStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *AvatarStorage) EXPECT() *AvatarStorage_Expecter {
	return &AvatarStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, path
func (_m *AvatarStorage) Delete(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AvatarStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AvatarStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *AvatarStorage_Expecter) Delete(ctx interface{}, path interface{}) *AvatarStorage_Delete_Call {
	return &AvatarStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, path)}
}

func (_c *AvatarStorage_Delete_Call) Run(run func(ctx context.Context, path string)) *AvatarStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *AvatarStorage_Delete_Call) Return(_a0 error) *AvatarStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AvatarStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *AvatarStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, input
func (_m *AvatarStorage) Save(ctx context.Context, input models.SaveUserAvatarInput) (models.SavedUserAvatar, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 models.SavedUserAvatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.SaveUserAvatarInput) (models.SavedUserAvatar, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.SaveUserAvatarInput) models.SavedUserAvatar); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.SavedUserAvatar)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.SaveUserAvatarInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AvatarStorage_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type AvatarStorage_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.SaveUserAvatarInput
func (_e *AvatarStorage_Expecter) Save(ctx interface{}, input interface{}) *AvatarStorage_Save_Call {
	return &AvatarStorage_Save_Call{Call: _e.mock.On("Save", ctx, input)}
}

func (_c *AvatarStorage_Save_Call) Run(run func(ctx context.Context, input models.SaveUserAvatarInput)) *AvatarStorage_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.SaveUserAvatarInput))
	})
	return _c
}

func (_c *AvatarStorage_Save_Call) Return(_a0 models.SavedUserAvatar, _a1 error) *AvatarStorage_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AvatarStorage_Save_Call) RunAndReturn(run func(context.Context, models.SaveUserAvatarInput) (models.SavedUserAvatar, error)) *AvatarStorage_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewAvatarStorage creates a new instance of AvatarStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAvatarStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *AvatarStorage {
	mock := &AvatarStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
