// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

type AdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminRepository) EXPECT() *AdminRepository_Expecter {
	return &AdminRepository_Expecter{mock: &_m.Mock}
}

// ChangeAdminUserRole provides a mock function with given fields: ctx, input
func (_m *AdminRepository) ChangeAdminUserRole(ctx context.Context, input models.ChangeAdminUserRoleInput) (models.AdminUser, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ChangeAdminUserRole")
	}

	var r0 models.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ChangeAdminUserRoleInput) (models.AdminUser, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ChangeAdminUserRoleInput) models.AdminUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AdminUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ChangeAdminUserRoleInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepository_ChangeAdminUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeAdminUserRole'
type AdminRepository_ChangeAdminUserRole_Call struct {
	*mock.Call
}

// ChangeAdminUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ChangeAdminUserRoleInput
func (_e *AdminRepository_Expecter) ChangeAdminUserRole(ctx interface{}, input interface{}) *AdminRepository_ChangeAdminUserRole_Call {
	return &AdminRepository_ChangeAdminUserRole_Call{Call: _e.mock.On("ChangeAdminUserRole", ctx, input)}
}

func (_c *AdminRepository_ChangeAdminUserRole_Call) Run(run func(ctx context.Context, input models.ChangeAdminUserRoleInput)) *AdminRepository_ChangeAdminUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ChangeAdminUserRoleInput))
	})
	return _c
}

func (_c *AdminRepository_ChangeAdminUserRole_Call) Return(_a0 models.AdminUser, _a1 error) *AdminRepository_ChangeAdminUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepository_ChangeAdminUserRole_Call) RunAndReturn(run func(context.Context, models.ChangeAdminUserRoleInput) (models.AdminUser, error)) *AdminRepository_ChangeAdminUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAdminAuditLog provides a mock function with given fields: ctx, audit
func (_m *AdminRepository) CreateAdminAuditLog(ctx context.Context, audit models.AdminAuditLog) (models.AdminAuditLog, error) {
	ret := _m.Called(ctx, audit)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdminAuditLog")
	}

	var r0 models.AdminAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminAuditLog) (models.AdminAuditLog, error)); ok {
		return rf(ctx, audit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminAuditLog) models.AdminAuditLog); ok {
		r0 = rf(ctx, audit)
	} else {
		r0 = ret.Get(0).(models.AdminAuditLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AdminAuditLog) error); ok {
		r1 = rf(ctx, audit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepository_CreateAdminAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAdminAuditLog'
type AdminRepository_CreateAdminAuditLog_Call struct {
	*mock.Call
}

// CreateAdminAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - audit models.AdminAuditLog
func (_e *AdminRepository_Expecter) CreateAdminAuditLog(ctx interface{}, audit interface{}) *AdminRepository_CreateAdminAuditLog_Call {
	return &AdminRepository_CreateAdminAuditLog_Call{Call: _e.mock.On("CreateAdminAuditLog", ctx, audit)}
}

func (_c *AdminRepository_CreateAdminAuditLog_Call) Run(run func(ctx context.Context, audit models.AdminAuditLog)) *AdminRepository_CreateAdminAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AdminAuditLog))
	})
	return _c
}

func (_c *AdminRepository_CreateAdminAuditLog_Call) Return(_a0 models.AdminAuditLog, _a1 error) *AdminRepository_CreateAdminAuditLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepository_CreateAdminAuditLog_Call) RunAndReturn(run func(context.Context, models.AdminAuditLog) (models.AdminAuditLog, error)) *AdminRepository_CreateAdminAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// GetAdminUserByUUID provides a mock function with given fields: ctx, userID
func (_m *AdminRepository) GetAdminUserByUUID(ctx context.Context, userID uuid.UUID) (models.AdminUser, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAdminUserByUUID")
	}

	var r0 models.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.AdminUser, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.AdminUser); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.AdminUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepository_GetAdminUserByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAdminUserByUUID'
type AdminRepository_GetAdminUserByUUID_Call struct {
	*mock.Call
}

// GetAdminUserByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AdminRepository_Expecter) GetAdminUserByUUID(ctx interface{}, userID interface{}) *AdminRepository_GetAdminUserByUUID_Call {
	return &AdminRepository_GetAdminUserByUUID_Call{Call: _e.mock.On("GetAdminUserByUUID", ctx, userID)}
}

func (_c *AdminRepository_GetAdminUserByUUID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AdminRepository_GetAdminUserByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AdminRepository_GetAdminUserByUUID_Call) Return(_a0 models.AdminUser, _a1 error) *AdminRepository_GetAdminUserByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepository_GetAdminUserByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.AdminUser, error)) *AdminRepository_GetAdminUserByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdminUserSessions provides a mock function with given fields: ctx, userID
func (_m *AdminRepository) ListAdminUserSessions(ctx context.Context, userID uuid.UUID) ([]models.AdminUserSession, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAdminUserSessions")
	}

	var r0 []models.AdminUserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.AdminUserSession, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.AdminUserSession); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminUserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepository_ListAdminUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdminUserSessions'
type AdminRepository_ListAdminUserSessions_Call struct {
	*mock.Call
}

// ListAdminUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AdminRepository_Expecter) ListAdminUserSessions(ctx interface{}, userID interface{}) *AdminRepository_ListAdminUserSessions_Call {
	return &AdminRepository_ListAdminUserSessions_Call{Call: _e.mock.On("ListAdminUserSessions", ctx, userID)}
}

func (_c *AdminRepository_ListAdminUserSessions_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AdminRepository_ListAdminUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AdminRepository_ListAdminUserSessions_Call) Return(_a0 []models.AdminUserSession, _a1 error) *AdminRepository_ListAdminUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepository_ListAdminUserSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.AdminUserSession, error)) *AdminRepository_ListAdminUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdminUsers provides a mock function with given fields: ctx, input
func (_m *AdminRepository) ListAdminUsers(ctx context.Context, input models.ListAdminUsersInput) (models.ListAdminUsersResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListAdminUsers")
	}

	var r0 models.ListAdminUsersResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListAdminUsersInput) (models.ListAdminUsersResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListAdminUsersInput) models.ListAdminUsersResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ListAdminUsersResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListAdminUsersInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepository_ListAdminUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdminUsers'
type AdminRepository_ListAdminUsers_Call struct {
	*mock.Call
}

// ListAdminUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListAdminUsersInput
func (_e *AdminRepository_Expecter) ListAdminUsers(ctx interface{}, input interface{}) *AdminRepository_ListAdminUsers_Call {
	return &AdminRepository_ListAdminUsers_Call{Call: _e.mock.On("ListAdminUsers", ctx, input)}
}

func (_c *AdminRepository_ListAdminUsers_Call) Run(run func(ctx context.Context, input models.ListAdminUsersInput)) *AdminRepository_ListAdminUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListAdminUsersInput))
	})
	return _c
}

func (_c *AdminRepository_ListAdminUsers_Call) Return(_a0 models.ListAdminUsersResult, _a1 error) *AdminRepository_ListAdminUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepository_ListAdminUsers_Call) RunAndReturn(run func(context.Context, models.ListAdminUsersInput) (models.ListAdminUsersResult, error)) *AdminRepository_ListAdminUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAdminUserSession provides a mock function with given fields: ctx, input
func (_m *AdminRepository) RevokeAdminUserSession(ctx context.Context, input models.AdminSessionMutationInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAdminUserSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminSessionMutationInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminRepository_RevokeAdminUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAdminUserSession'
type AdminRepository_RevokeAdminUserSession_Call struct {
	*mock.Call
}

// RevokeAdminUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AdminSessionMutationInput
func (_e *AdminRepository_Expecter) RevokeAdminUserSession(ctx interface{}, input interface{}) *AdminRepository_RevokeAdminUserSession_Call {
	return &AdminRepository_RevokeAdminUserSession_Call{Call: _e.mock.On("RevokeAdminUserSession", ctx, input)}
}

func (_c *AdminRepository_RevokeAdminUserSession_Call) Run(run func(ctx context.Context, input models.AdminSessionMutationInput)) *AdminRepository_RevokeAdminUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AdminSessionMutationInput))
	})
	return _c
}

func (_c *AdminRepository_RevokeAdminUserSession_Call) Return(_a0 error) *AdminRepository_RevokeAdminUserSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminRepository_RevokeAdminUserSession_Call) RunAndReturn(run func(context.Context, models.AdminSessionMutationInput) error) *AdminRepository_RevokeAdminUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllAdminUserSessions provides a mock function with given fields: ctx, input
func (_m *AdminRepository) RevokeAllAdminUserSessions(ctx context.Context, input models.AdminSessionMutationInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllAdminUserSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminSessionMutationInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminRepository_RevokeAllAdminUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllAdminUserSessions'
type AdminRepository_RevokeAllAdminUserSessions_Call struct {
	*mock.Call
}

// RevokeAllAdminUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AdminSessionMutationInput
func (_e *AdminRepository_Expecter) RevokeAllAdminUserSessions(ctx interface{}, input interface{}) *AdminRepository_RevokeAllAdminUserSessions_Call {
	return &AdminRepository_RevokeAllAdminUserSessions_Call{Call: _e.mock.On("RevokeAllAdminUserSessions", ctx, input)}
}

func (_c *AdminRepository_RevokeAllAdminUserSessions_Call) Run(run func(ctx context.Context, input models.AdminSessionMutationInput)) *AdminRepository_RevokeAllAdminUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AdminSessionMutationInput))
	})
	return _c
}

func (_c *AdminRepository_RevokeAllAdminUserSessions_Call) Return(_a0 error) *AdminRepository_RevokeAllAdminUserSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminRepository_RevokeAllAdminUserSessions_Call) RunAndReturn(run func(context.Context, models.AdminSessionMutationInput) error) *AdminRepository_RevokeAllAdminUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
