// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AdminRepository is an autogenerated mock type for the AdminRepository type
type AdminRepository struct {
	mock.Mock
}

type AdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminRepository) EXPECT() *AdminRepository_Expecter {
	return &AdminRepository_Expecter{mock: &_m.Mock}
}

// CreateAdminAuditLog provides a mock function with given fields: ctx, audit
func (_m *AdminRepository) CreateAdminAuditLog(ctx context.Context, audit models.AdminAuditLog) (models.AdminAuditLog, error) {
	ret := _m.Called(ctx, audit)

	if len(ret) == 0 {
		panic("no return value specified for CreateAdminAuditLog")
	}

	var r0 models.AdminAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminAuditLog) (models.AdminAuditLog, error)); ok {
		return rf(ctx, audit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminAuditLog) models.AdminAuditLog); ok {
		r0 = rf(ctx, audit)
	} else {
		r0 = ret.Get(0).(models.AdminAuditLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AdminAuditLog) error); ok {
		r1 = rf(ctx, audit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminRepository_CreateAdminAuditLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAdminAuditLog'
type AdminRepository_CreateAdminAuditLog_Call struct {
	*mock.Call
}

// CreateAdminAuditLog is a helper method to define mock.On call
//   - ctx context.Context
//   - audit models.AdminAuditLog
func (_e *AdminRepository_Expecter) CreateAdminAuditLog(ctx interface{}, audit interface{}) *AdminRepository_CreateAdminAuditLog_Call {
	return &AdminRepository_CreateAdminAuditLog_Call{Call: _e.mock.On("CreateAdminAuditLog", ctx, audit)}
}

func (_c *AdminRepository_CreateAdminAuditLog_Call) Run(run func(ctx context.Context, audit models.AdminAuditLog)) *AdminRepository_CreateAdminAuditLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AdminAuditLog))
	})
	return _c
}

func (_c *AdminRepository_CreateAdminAuditLog_Call) Return(_a0 models.AdminAuditLog, _a1 error) *AdminRepository_CreateAdminAuditLog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminRepository_CreateAdminAuditLog_Call) RunAndReturn(run func(context.Context, models.AdminAuditLog) (models.AdminAuditLog, error)) *AdminRepository_CreateAdminAuditLog_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdminRepository creates a new instance of AdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepository {
	mock := &AdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
