// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// BillingLimiter is an autogenerated mock type for the BillingLimiter type
type BillingLimiter struct {
	mock.Mock
}

type BillingLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *BillingLimiter) EXPECT() *BillingLimiter_Expecter {
	return &BillingLimiter_Expecter{mock: &_m.Mock}
}

// CanAddCompanyMember provides a mock function with given fields: ctx, companyID
func (_m *BillingLimiter) CanAddCompanyMember(ctx context.Context, companyID uuid.UUID) error {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for CanAddCompanyMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanAddCompanyMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAddCompanyMember'
type BillingLimiter_CanAddCompanyMember_Call struct {
	*mock.Call
}

// CanAddCompanyMember is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *BillingLimiter_Expecter) CanAddCompanyMember(ctx interface{}, companyID interface{}) *BillingLimiter_CanAddCompanyMember_Call {
	return &BillingLimiter_CanAddCompanyMember_Call{Call: _e.mock.On("CanAddCompanyMember", ctx, companyID)}
}

func (_c *BillingLimiter_CanAddCompanyMember_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *BillingLimiter_CanAddCompanyMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_CanAddCompanyMember_Call) Return(_a0 error) *BillingLimiter_CanAddCompanyMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanAddCompanyMember_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *BillingLimiter_CanAddCompanyMember_Call {
	_c.Call.Return(run)
	return _c
}

// CanUseCompany provides a mock function with given fields: ctx, companyID
func (_m *BillingLimiter) CanUseCompany(ctx context.Context, companyID uuid.UUID) error {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for CanUseCompany")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanUseCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUseCompany'
type BillingLimiter_CanUseCompany_Call struct {
	*mock.Call
}

// CanUseCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *BillingLimiter_Expecter) CanUseCompany(ctx interface{}, companyID interface{}) *BillingLimiter_CanUseCompany_Call {
	return &BillingLimiter_CanUseCompany_Call{Call: _e.mock.On("CanUseCompany", ctx, companyID)}
}

func (_c *BillingLimiter_CanUseCompany_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *BillingLimiter_CanUseCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_CanUseCompany_Call) Return(_a0 error) *BillingLimiter_CanUseCompany_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanUseCompany_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *BillingLimiter_CanUseCompany_Call {
	_c.Call.Return(run)
	return _c
}

// NewBillingLimiter creates a new instance of BillingLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingLimiter {
	mock := &BillingLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
