// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// DepartmentService is an autogenerated mock type for the DepartmentService type
type DepartmentService struct {
	mock.Mock
}

type DepartmentService_Expecter struct {
	mock *mock.Mock
}

func (_m *DepartmentService) EXPECT() *DepartmentService_Expecter {
	return &DepartmentService_Expecter{mock: &_m.Mock}
}

// AddDepartmentMember provides a mock function with given fields: ctx, input
func (_m *DepartmentService) AddDepartmentMember(ctx context.Context, input models.AddDepartmentMemberInput) (models.DepartmentMember, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddDepartmentMember")
	}

	var r0 models.DepartmentMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AddDepartmentMemberInput) (models.DepartmentMember, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AddDepartmentMemberInput) models.DepartmentMember); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.DepartmentMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AddDepartmentMemberInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepartmentService_AddDepartmentMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDepartmentMember'
type DepartmentService_AddDepartmentMember_Call struct {
	*mock.Call
}

// AddDepartmentMember is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AddDepartmentMemberInput
func (_e *DepartmentService_Expecter) AddDepartmentMember(ctx interface{}, input interface{}) *DepartmentService_AddDepartmentMember_Call {
	return &DepartmentService_AddDepartmentMember_Call{Call: _e.mock.On("AddDepartmentMember", ctx, input)}
}

func (_c *DepartmentService_AddDepartmentMember_Call) Run(run func(ctx context.Context, input models.AddDepartmentMemberInput)) *DepartmentService_AddDepartmentMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AddDepartmentMemberInput))
	})
	return _c
}

func (_c *DepartmentService_AddDepartmentMember_Call) Return(_a0 models.DepartmentMember, _a1 error) *DepartmentService_AddDepartmentMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepartmentService_AddDepartmentMember_Call) RunAndReturn(run func(context.Context, models.AddDepartmentMemberInput) (models.DepartmentMember, error)) *DepartmentService_AddDepartmentMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDepartment provides a mock function with given fields: ctx, input
func (_m *DepartmentService) CreateDepartment(ctx context.Context, input models.CreateDepartmentInput) (models.Department, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateDepartment")
	}

	var r0 models.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDepartmentInput) (models.Department, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDepartmentInput) models.Department); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.Department)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateDepartmentInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepartmentService_CreateDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDepartment'
type DepartmentService_CreateDepartment_Call struct {
	*mock.Call
}

// CreateDepartment is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateDepartmentInput
func (_e *DepartmentService_Expecter) CreateDepartment(ctx interface{}, input interface{}) *DepartmentService_CreateDepartment_Call {
	return &DepartmentService_CreateDepartment_Call{Call: _e.mock.On("CreateDepartment", ctx, input)}
}

func (_c *DepartmentService_CreateDepartment_Call) Run(run func(ctx context.Context, input models.CreateDepartmentInput)) *DepartmentService_CreateDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateDepartmentInput))
	})
	return _c
}

func (_c *DepartmentService_CreateDepartment_Call) Return(_a0 models.Department, _a1 error) *DepartmentService_CreateDepartment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepartmentService_CreateDepartment_Call) RunAndReturn(run func(context.Context, models.CreateDepartmentInput) (models.Department, error)) *DepartmentService_CreateDepartment_Call {
	_c.Call.Return(run)
	return _c
}

// ListCompanyDepartments provides a mock function with given fields: ctx, companyID, userID
func (_m *DepartmentService) ListCompanyDepartments(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) ([]models.Department, error) {
	ret := _m.Called(ctx, companyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListCompanyDepartments")
	}

	var r0 []models.Department
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.Department, error)); ok {
		return rf(ctx, companyID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.Department); ok {
		r0 = rf(ctx, companyID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Department)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepartmentService_ListCompanyDepartments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCompanyDepartments'
type DepartmentService_ListCompanyDepartments_Call struct {
	*mock.Call
}

// ListCompanyDepartments is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - userID uuid.UUID
func (_e *DepartmentService_Expecter) ListCompanyDepartments(ctx interface{}, companyID interface{}, userID interface{}) *DepartmentService_ListCompanyDepartments_Call {
	return &DepartmentService_ListCompanyDepartments_Call{Call: _e.mock.On("ListCompanyDepartments", ctx, companyID, userID)}
}

func (_c *DepartmentService_ListCompanyDepartments_Call) Run(run func(ctx context.Context, companyID uuid.UUID, userID uuid.UUID)) *DepartmentService_ListCompanyDepartments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *DepartmentService_ListCompanyDepartments_Call) Return(_a0 []models.Department, _a1 error) *DepartmentService_ListCompanyDepartments_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepartmentService_ListCompanyDepartments_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.Department, error)) *DepartmentService_ListCompanyDepartments_Call {
	_c.Call.Return(run)
	return _c
}

// ListDepartmentMembers provides a mock function with given fields: ctx, companyID, departmentID, userID
func (_m *DepartmentService) ListDepartmentMembers(ctx context.Context, companyID uuid.UUID, departmentID uuid.UUID, userID uuid.UUID) ([]models.DepartmentMember, error) {
	ret := _m.Called(ctx, companyID, departmentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListDepartmentMembers")
	}

	var r0 []models.DepartmentMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) ([]models.DepartmentMember, error)); ok {
		return rf(ctx, companyID, departmentID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) []models.DepartmentMember); ok {
		r0 = rf(ctx, companyID, departmentID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.DepartmentMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID, departmentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepartmentService_ListDepartmentMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDepartmentMembers'
type DepartmentService_ListDepartmentMembers_Call struct {
	*mock.Call
}

// ListDepartmentMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - departmentID uuid.UUID
//   - userID uuid.UUID
func (_e *DepartmentService_Expecter) ListDepartmentMembers(ctx interface{}, companyID interface{}, departmentID interface{}, userID interface{}) *DepartmentService_ListDepartmentMembers_Call {
	return &DepartmentService_ListDepartmentMembers_Call{Call: _e.mock.On("ListDepartmentMembers", ctx, companyID, departmentID, userID)}
}

func (_c *DepartmentService_ListDepartmentMembers_Call) Run(run func(ctx context.Context, companyID uuid.UUID, departmentID uuid.UUID, userID uuid.UUID)) *DepartmentService_ListDepartmentMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *DepartmentService_ListDepartmentMembers_Call) Return(_a0 []models.DepartmentMember, _a1 error) *DepartmentService_ListDepartmentMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepartmentService_ListDepartmentMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) ([]models.DepartmentMember, error)) *DepartmentService_ListDepartmentMembers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDepartmentMemberRole provides a mock function with given fields: ctx, input
func (_m *DepartmentService) UpdateDepartmentMemberRole(ctx context.Context, input models.UpdateDepartmentMemberRoleInput) (models.DepartmentMember, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDepartmentMemberRole")
	}

	var r0 models.DepartmentMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateDepartmentMemberRoleInput) (models.DepartmentMember, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateDepartmentMemberRoleInput) models.DepartmentMember); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.DepartmentMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateDepartmentMemberRoleInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepartmentService_UpdateDepartmentMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartmentMemberRole'
type DepartmentService_UpdateDepartmentMemberRole_Call struct {
	*mock.Call
}

// UpdateDepartmentMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateDepartmentMemberRoleInput
func (_e *DepartmentService_Expecter) UpdateDepartmentMemberRole(ctx interface{}, input interface{}) *DepartmentService_UpdateDepartmentMemberRole_Call {
	return &DepartmentService_UpdateDepartmentMemberRole_Call{Call: _e.mock.On("UpdateDepartmentMemberRole", ctx, input)}
}

func (_c *DepartmentService_UpdateDepartmentMemberRole_Call) Run(run func(ctx context.Context, input models.UpdateDepartmentMemberRoleInput)) *DepartmentService_UpdateDepartmentMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateDepartmentMemberRoleInput))
	})
	return _c
}

func (_c *DepartmentService_UpdateDepartmentMemberRole_Call) Return(_a0 models.DepartmentMember, _a1 error) *DepartmentService_UpdateDepartmentMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepartmentService_UpdateDepartmentMemberRole_Call) RunAndReturn(run func(context.Context, models.UpdateDepartmentMemberRoleInput) (models.DepartmentMember, error)) *DepartmentService_UpdateDepartmentMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDepartmentMemberStatus provides a mock function with given fields: ctx, input
func (_m *DepartmentService) UpdateDepartmentMemberStatus(ctx context.Context, input models.UpdateDepartmentMemberStatusInput) (models.DepartmentMember, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDepartmentMemberStatus")
	}

	var r0 models.DepartmentMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateDepartmentMemberStatusInput) (models.DepartmentMember, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateDepartmentMemberStatusInput) models.DepartmentMember); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.DepartmentMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateDepartmentMemberStatusInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepartmentService_UpdateDepartmentMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartmentMemberStatus'
type DepartmentService_UpdateDepartmentMemberStatus_Call struct {
	*mock.Call
}

// UpdateDepartmentMemberStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateDepartmentMemberStatusInput
func (_e *DepartmentService_Expecter) UpdateDepartmentMemberStatus(ctx interface{}, input interface{}) *DepartmentService_UpdateDepartmentMemberStatus_Call {
	return &DepartmentService_UpdateDepartmentMemberStatus_Call{Call: _e.mock.On("UpdateDepartmentMemberStatus", ctx, input)}
}

func (_c *DepartmentService_UpdateDepartmentMemberStatus_Call) Run(run func(ctx context.Context, input models.UpdateDepartmentMemberStatusInput)) *DepartmentService_UpdateDepartmentMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateDepartmentMemberStatusInput))
	})
	return _c
}

func (_c *DepartmentService_UpdateDepartmentMemberStatus_Call) Return(_a0 models.DepartmentMember, _a1 error) *DepartmentService_UpdateDepartmentMemberStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DepartmentService_UpdateDepartmentMemberStatus_Call) RunAndReturn(run func(context.Context, models.UpdateDepartmentMemberStatusInput) (models.DepartmentMember, error)) *DepartmentService_UpdateDepartmentMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewDepartmentService creates a new instance of DepartmentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentService {
	mock := &DepartmentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
