// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AnalyticsService is an autogenerated mock type for the AnalyticsService type
type AnalyticsService struct {
	mock.Mock
}

type AnalyticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalyticsService) EXPECT() *AnalyticsService_Expecter {
	return &AnalyticsService_Expecter{mock: &_m.Mock}
}

// CreateDeepAnalysis provides a mock function with given fields: ctx, input
func (_m *AnalyticsService) CreateDeepAnalysis(ctx context.Context, input models.CreateDeepAnalysisInput) (models.AggregateAnalysis, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeepAnalysis")
	}

	var r0 models.AggregateAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDeepAnalysisInput) (models.AggregateAnalysis, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateDeepAnalysisInput) models.AggregateAnalysis); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AggregateAnalysis)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateDeepAnalysisInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_CreateDeepAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeepAnalysis'
type AnalyticsService_CreateDeepAnalysis_Call struct {
	*mock.Call
}

// CreateDeepAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateDeepAnalysisInput
func (_e *AnalyticsService_Expecter) CreateDeepAnalysis(ctx interface{}, input interface{}) *AnalyticsService_CreateDeepAnalysis_Call {
	return &AnalyticsService_CreateDeepAnalysis_Call{Call: _e.mock.On("CreateDeepAnalysis", ctx, input)}
}

func (_c *AnalyticsService_CreateDeepAnalysis_Call) Run(run func(ctx context.Context, input models.CreateDeepAnalysisInput)) *AnalyticsService_CreateDeepAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateDeepAnalysisInput))
	})
	return _c
}

func (_c *AnalyticsService_CreateDeepAnalysis_Call) Return(_a0 models.AggregateAnalysis, _a1 error) *AnalyticsService_CreateDeepAnalysis_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_CreateDeepAnalysis_Call) RunAndReturn(run func(context.Context, models.CreateDeepAnalysisInput) (models.AggregateAnalysis, error)) *AnalyticsService_CreateDeepAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeepAnalysis provides a mock function with given fields: ctx, id, userID
func (_m *AnalyticsService) GetDeepAnalysis(ctx context.Context, id uuid.UUID, userID uuid.UUID) (models.AggregateAnalysis, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeepAnalysis")
	}

	var r0 models.AggregateAnalysis
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.AggregateAnalysis, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.AggregateAnalysis); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Get(0).(models.AggregateAnalysis)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_GetDeepAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeepAnalysis'
type AnalyticsService_GetDeepAnalysis_Call struct {
	*mock.Call
}

// GetDeepAnalysis is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *AnalyticsService_Expecter) GetDeepAnalysis(ctx interface{}, id interface{}, userID interface{}) *AnalyticsService_GetDeepAnalysis_Call {
	return &AnalyticsService_GetDeepAnalysis_Call{Call: _e.mock.On("GetDeepAnalysis", ctx, id, userID)}
}

func (_c *AnalyticsService_GetDeepAnalysis_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *AnalyticsService_GetDeepAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AnalyticsService_GetDeepAnalysis_Call) Return(_a0 models.AggregateAnalysis, _a1 error) *AnalyticsService_GetDeepAnalysis_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_GetDeepAnalysis_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.AggregateAnalysis, error)) *AnalyticsService_GetDeepAnalysis_Call {
	_c.Call.Return(run)
	return _c
}

// GetOverview provides a mock function with given fields: ctx, input
func (_m *AnalyticsService) GetOverview(ctx context.Context, input models.AnalyticsOverviewInput) (models.AnalyticsOverview, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetOverview")
	}

	var r0 models.AnalyticsOverview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AnalyticsOverviewInput) (models.AnalyticsOverview, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AnalyticsOverviewInput) models.AnalyticsOverview); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AnalyticsOverview)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AnalyticsOverviewInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type AnalyticsService_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AnalyticsOverviewInput
func (_e *AnalyticsService_Expecter) GetOverview(ctx interface{}, input interface{}) *AnalyticsService_GetOverview_Call {
	return &AnalyticsService_GetOverview_Call{Call: _e.mock.On("GetOverview", ctx, input)}
}

func (_c *AnalyticsService_GetOverview_Call) Run(run func(ctx context.Context, input models.AnalyticsOverviewInput)) *AnalyticsService_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AnalyticsOverviewInput))
	})
	return _c
}

func (_c *AnalyticsService_GetOverview_Call) Return(_a0 models.AnalyticsOverview, _a1 error) *AnalyticsService_GetOverview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_GetOverview_Call) RunAndReturn(run func(context.Context, models.AnalyticsOverviewInput) (models.AnalyticsOverview, error)) *AnalyticsService_GetOverview_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeepAnalyses provides a mock function with given fields: ctx, input
func (_m *AnalyticsService) ListDeepAnalyses(ctx context.Context, input models.ListDeepAnalysesInput) (models.ListAggregateAnalysesResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListDeepAnalyses")
	}

	var r0 models.ListAggregateAnalysesResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListDeepAnalysesInput) (models.ListAggregateAnalysesResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListDeepAnalysesInput) models.ListAggregateAnalysesResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ListAggregateAnalysesResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListDeepAnalysesInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AnalyticsService_ListDeepAnalyses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeepAnalyses'
type AnalyticsService_ListDeepAnalyses_Call struct {
	*mock.Call
}

// ListDeepAnalyses is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListDeepAnalysesInput
func (_e *AnalyticsService_Expecter) ListDeepAnalyses(ctx interface{}, input interface{}) *AnalyticsService_ListDeepAnalyses_Call {
	return &AnalyticsService_ListDeepAnalyses_Call{Call: _e.mock.On("ListDeepAnalyses", ctx, input)}
}

func (_c *AnalyticsService_ListDeepAnalyses_Call) Run(run func(ctx context.Context, input models.ListDeepAnalysesInput)) *AnalyticsService_ListDeepAnalyses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListDeepAnalysesInput))
	})
	return _c
}

func (_c *AnalyticsService_ListDeepAnalyses_Call) Return(_a0 models.ListAggregateAnalysesResult, _a1 error) *AnalyticsService_ListDeepAnalyses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AnalyticsService_ListDeepAnalyses_Call) RunAndReturn(run func(context.Context, models.ListDeepAnalysesInput) (models.ListAggregateAnalysesResult, error)) *AnalyticsService_ListDeepAnalyses_Call {
	_c.Call.Return(run)
	return _c
}

// NewAnalyticsService creates a new instance of AnalyticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsService {
	mock := &AnalyticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
