// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

type AdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminService) EXPECT() *AdminService_Expecter {
	return &AdminService_Expecter{mock: &_m.Mock}
}

// GetCapabilities provides a mock function with given fields: ctx, role
func (_m *AdminService) GetCapabilities(ctx context.Context, role models.UserRole) (models.AdminCapabilities, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 models.AdminCapabilities
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserRole) (models.AdminCapabilities, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserRole) models.AdminCapabilities); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(models.AdminCapabilities)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserRole) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type AdminService_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
//   - ctx context.Context
//   - role models.UserRole
func (_e *AdminService_Expecter) GetCapabilities(ctx interface{}, role interface{}) *AdminService_GetCapabilities_Call {
	return &AdminService_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities", ctx, role)}
}

func (_c *AdminService_GetCapabilities_Call) Run(run func(ctx context.Context, role models.UserRole)) *AdminService_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserRole))
	})
	return _c
}

func (_c *AdminService_GetCapabilities_Call) Return(_a0 models.AdminCapabilities, _a1 error) *AdminService_GetCapabilities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_GetCapabilities_Call) RunAndReturn(run func(context.Context, models.UserRole) (models.AdminCapabilities, error)) *AdminService_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// RecordAudit provides a mock function with given fields: ctx, input
func (_m *AdminService) RecordAudit(ctx context.Context, input models.CreateAdminAuditLogInput) (models.AdminAuditLog, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordAudit")
	}

	var r0 models.AdminAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateAdminAuditLogInput) (models.AdminAuditLog, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateAdminAuditLogInput) models.AdminAuditLog); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AdminAuditLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateAdminAuditLogInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_RecordAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAudit'
type AdminService_RecordAudit_Call struct {
	*mock.Call
}

// RecordAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateAdminAuditLogInput
func (_e *AdminService_Expecter) RecordAudit(ctx interface{}, input interface{}) *AdminService_RecordAudit_Call {
	return &AdminService_RecordAudit_Call{Call: _e.mock.On("RecordAudit", ctx, input)}
}

func (_c *AdminService_RecordAudit_Call) Run(run func(ctx context.Context, input models.CreateAdminAuditLogInput)) *AdminService_RecordAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateAdminAuditLogInput))
	})
	return _c
}

func (_c *AdminService_RecordAudit_Call) Return(_a0 models.AdminAuditLog, _a1 error) *AdminService_RecordAudit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_RecordAudit_Call) RunAndReturn(run func(context.Context, models.CreateAdminAuditLogInput) (models.AdminAuditLog, error)) *AdminService_RecordAudit_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
