// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CompanyService is an autogenerated mock type for the CompanyService type
type CompanyService struct {
	mock.Mock
}

type CompanyService_Expecter struct {
	mock *mock.Mock
}

func (_m *CompanyService) EXPECT() *CompanyService_Expecter {
	return &CompanyService_Expecter{mock: &_m.Mock}
}

// AddCompanyMember provides a mock function with given fields: ctx, input
func (_m *CompanyService) AddCompanyMember(ctx context.Context, input models.AddCompanyMemberInput) (models.CompanyMember, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddCompanyMember")
	}

	var r0 models.CompanyMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AddCompanyMemberInput) (models.CompanyMember, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.AddCompanyMemberInput) models.CompanyMember); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CompanyMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.AddCompanyMemberInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_AddCompanyMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCompanyMember'
type CompanyService_AddCompanyMember_Call struct {
	*mock.Call
}

// AddCompanyMember is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AddCompanyMemberInput
func (_e *CompanyService_Expecter) AddCompanyMember(ctx interface{}, input interface{}) *CompanyService_AddCompanyMember_Call {
	return &CompanyService_AddCompanyMember_Call{Call: _e.mock.On("AddCompanyMember", ctx, input)}
}

func (_c *CompanyService_AddCompanyMember_Call) Run(run func(ctx context.Context, input models.AddCompanyMemberInput)) *CompanyService_AddCompanyMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AddCompanyMemberInput))
	})
	return _c
}

func (_c *CompanyService_AddCompanyMember_Call) Return(_a0 models.CompanyMember, _a1 error) *CompanyService_AddCompanyMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_AddCompanyMember_Call) RunAndReturn(run func(context.Context, models.AddCompanyMemberInput) (models.CompanyMember, error)) *CompanyService_AddCompanyMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateCompany provides a mock function with given fields: ctx, input
func (_m *CompanyService) CreateCompany(ctx context.Context, input models.CreateCompanyInput) (models.Company, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCompany")
	}

	var r0 models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateCompanyInput) (models.Company, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateCompanyInput) models.Company); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.Company)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateCompanyInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_CreateCompany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCompany'
type CompanyService_CreateCompany_Call struct {
	*mock.Call
}

// CreateCompany is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateCompanyInput
func (_e *CompanyService_Expecter) CreateCompany(ctx interface{}, input interface{}) *CompanyService_CreateCompany_Call {
	return &CompanyService_CreateCompany_Call{Call: _e.mock.On("CreateCompany", ctx, input)}
}

func (_c *CompanyService_CreateCompany_Call) Run(run func(ctx context.Context, input models.CreateCompanyInput)) *CompanyService_CreateCompany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateCompanyInput))
	})
	return _c
}

func (_c *CompanyService_CreateCompany_Call) Return(_a0 models.Company, _a1 error) *CompanyService_CreateCompany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_CreateCompany_Call) RunAndReturn(run func(context.Context, models.CreateCompanyInput) (models.Company, error)) *CompanyService_CreateCompany_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyByUUID provides a mock function with given fields: ctx, companyID, userID
func (_m *CompanyService) GetCompanyByUUID(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) (models.Company, error) {
	ret := _m.Called(ctx, companyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyByUUID")
	}

	var r0 models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.Company, error)); ok {
		return rf(ctx, companyID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.Company); ok {
		r0 = rf(ctx, companyID, userID)
	} else {
		r0 = ret.Get(0).(models.Company)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_GetCompanyByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyByUUID'
type CompanyService_GetCompanyByUUID_Call struct {
	*mock.Call
}

// GetCompanyByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - userID uuid.UUID
func (_e *CompanyService_Expecter) GetCompanyByUUID(ctx interface{}, companyID interface{}, userID interface{}) *CompanyService_GetCompanyByUUID_Call {
	return &CompanyService_GetCompanyByUUID_Call{Call: _e.mock.On("GetCompanyByUUID", ctx, companyID, userID)}
}

func (_c *CompanyService_GetCompanyByUUID_Call) Run(run func(ctx context.Context, companyID uuid.UUID, userID uuid.UUID)) *CompanyService_GetCompanyByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyService_GetCompanyByUUID_Call) Return(_a0 models.Company, _a1 error) *CompanyService_GetCompanyByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_GetCompanyByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.Company, error)) *CompanyService_GetCompanyByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCompanyMembersOverview provides a mock function with given fields: ctx, companyID, userID
func (_m *CompanyService) GetCompanyMembersOverview(ctx context.Context, companyID uuid.UUID, userID uuid.UUID) (models.CompanyMembersOverview, error) {
	ret := _m.Called(ctx, companyID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCompanyMembersOverview")
	}

	var r0 models.CompanyMembersOverview
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (models.CompanyMembersOverview, error)); ok {
		return rf(ctx, companyID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) models.CompanyMembersOverview); ok {
		r0 = rf(ctx, companyID, userID)
	} else {
		r0 = ret.Get(0).(models.CompanyMembersOverview)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, companyID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_GetCompanyMembersOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCompanyMembersOverview'
type CompanyService_GetCompanyMembersOverview_Call struct {
	*mock.Call
}

// GetCompanyMembersOverview is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - userID uuid.UUID
func (_e *CompanyService_Expecter) GetCompanyMembersOverview(ctx interface{}, companyID interface{}, userID interface{}) *CompanyService_GetCompanyMembersOverview_Call {
	return &CompanyService_GetCompanyMembersOverview_Call{Call: _e.mock.On("GetCompanyMembersOverview", ctx, companyID, userID)}
}

func (_c *CompanyService_GetCompanyMembersOverview_Call) Run(run func(ctx context.Context, companyID uuid.UUID, userID uuid.UUID)) *CompanyService_GetCompanyMembersOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyService_GetCompanyMembersOverview_Call) Return(_a0 models.CompanyMembersOverview, _a1 error) *CompanyService_GetCompanyMembersOverview_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_GetCompanyMembersOverview_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (models.CompanyMembersOverview, error)) *CompanyService_GetCompanyMembersOverview_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserCompanies provides a mock function with given fields: ctx, userID
func (_m *CompanyService) ListUserCompanies(ctx context.Context, userID uuid.UUID) ([]models.Company, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserCompanies")
	}

	var r0 []models.Company
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.Company, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.Company); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Company)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_ListUserCompanies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserCompanies'
type CompanyService_ListUserCompanies_Call struct {
	*mock.Call
}

// ListUserCompanies is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *CompanyService_Expecter) ListUserCompanies(ctx interface{}, userID interface{}) *CompanyService_ListUserCompanies_Call {
	return &CompanyService_ListUserCompanies_Call{Call: _e.mock.On("ListUserCompanies", ctx, userID)}
}

func (_c *CompanyService_ListUserCompanies_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *CompanyService_ListUserCompanies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CompanyService_ListUserCompanies_Call) Return(_a0 []models.Company, _a1 error) *CompanyService_ListUserCompanies_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_ListUserCompanies_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]models.Company, error)) *CompanyService_ListUserCompanies_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompanyMemberRole provides a mock function with given fields: ctx, input
func (_m *CompanyService) UpdateCompanyMemberRole(ctx context.Context, input models.UpdateCompanyMemberRoleInput) (models.CompanyMember, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompanyMemberRole")
	}

	var r0 models.CompanyMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateCompanyMemberRoleInput) (models.CompanyMember, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateCompanyMemberRoleInput) models.CompanyMember); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CompanyMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateCompanyMemberRoleInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_UpdateCompanyMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompanyMemberRole'
type CompanyService_UpdateCompanyMemberRole_Call struct {
	*mock.Call
}

// UpdateCompanyMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateCompanyMemberRoleInput
func (_e *CompanyService_Expecter) UpdateCompanyMemberRole(ctx interface{}, input interface{}) *CompanyService_UpdateCompanyMemberRole_Call {
	return &CompanyService_UpdateCompanyMemberRole_Call{Call: _e.mock.On("UpdateCompanyMemberRole", ctx, input)}
}

func (_c *CompanyService_UpdateCompanyMemberRole_Call) Run(run func(ctx context.Context, input models.UpdateCompanyMemberRoleInput)) *CompanyService_UpdateCompanyMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateCompanyMemberRoleInput))
	})
	return _c
}

func (_c *CompanyService_UpdateCompanyMemberRole_Call) Return(_a0 models.CompanyMember, _a1 error) *CompanyService_UpdateCompanyMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_UpdateCompanyMemberRole_Call) RunAndReturn(run func(context.Context, models.UpdateCompanyMemberRoleInput) (models.CompanyMember, error)) *CompanyService_UpdateCompanyMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCompanyMemberStatus provides a mock function with given fields: ctx, input
func (_m *CompanyService) UpdateCompanyMemberStatus(ctx context.Context, input models.UpdateCompanyMemberStatusInput) (models.CompanyMember, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCompanyMemberStatus")
	}

	var r0 models.CompanyMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateCompanyMemberStatusInput) (models.CompanyMember, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UpdateCompanyMemberStatusInput) models.CompanyMember); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.CompanyMember)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UpdateCompanyMemberStatusInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CompanyService_UpdateCompanyMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCompanyMemberStatus'
type CompanyService_UpdateCompanyMemberStatus_Call struct {
	*mock.Call
}

// UpdateCompanyMemberStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.UpdateCompanyMemberStatusInput
func (_e *CompanyService_Expecter) UpdateCompanyMemberStatus(ctx interface{}, input interface{}) *CompanyService_UpdateCompanyMemberStatus_Call {
	return &CompanyService_UpdateCompanyMemberStatus_Call{Call: _e.mock.On("UpdateCompanyMemberStatus", ctx, input)}
}

func (_c *CompanyService_UpdateCompanyMemberStatus_Call) Run(run func(ctx context.Context, input models.UpdateCompanyMemberStatusInput)) *CompanyService_UpdateCompanyMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UpdateCompanyMemberStatusInput))
	})
	return _c
}

func (_c *CompanyService_UpdateCompanyMemberStatus_Call) Return(_a0 models.CompanyMember, _a1 error) *CompanyService_UpdateCompanyMemberStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CompanyService_UpdateCompanyMemberStatus_Call) RunAndReturn(run func(context.Context, models.UpdateCompanyMemberStatusInput) (models.CompanyMember, error)) *CompanyService_UpdateCompanyMemberStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewCompanyService creates a new instance of CompanyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCompanyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CompanyService {
	mock := &CompanyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
