// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	models "calllens/monolit/internal/models"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

type AdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminService) EXPECT() *AdminService_Expecter {
	return &AdminService_Expecter{mock: &_m.Mock}
}

// ChangeUserRole provides a mock function with given fields: ctx, input
func (_m *AdminService) ChangeUserRole(ctx context.Context, input models.ChangeAdminUserRoleInput) (models.AdminUser, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ChangeUserRole")
	}

	var r0 models.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ChangeAdminUserRoleInput) (models.AdminUser, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ChangeAdminUserRoleInput) models.AdminUser); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AdminUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ChangeAdminUserRoleInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_ChangeUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeUserRole'
type AdminService_ChangeUserRole_Call struct {
	*mock.Call
}

// ChangeUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ChangeAdminUserRoleInput
func (_e *AdminService_Expecter) ChangeUserRole(ctx interface{}, input interface{}) *AdminService_ChangeUserRole_Call {
	return &AdminService_ChangeUserRole_Call{Call: _e.mock.On("ChangeUserRole", ctx, input)}
}

func (_c *AdminService_ChangeUserRole_Call) Run(run func(ctx context.Context, input models.ChangeAdminUserRoleInput)) *AdminService_ChangeUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ChangeAdminUserRoleInput))
	})
	return _c
}

func (_c *AdminService_ChangeUserRole_Call) Return(_a0 models.AdminUser, _a1 error) *AdminService_ChangeUserRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_ChangeUserRole_Call) RunAndReturn(run func(context.Context, models.ChangeAdminUserRoleInput) (models.AdminUser, error)) *AdminService_ChangeUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetCapabilities provides a mock function with given fields: ctx, role
func (_m *AdminService) GetCapabilities(ctx context.Context, role models.UserRole) (models.AdminCapabilities, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetCapabilities")
	}

	var r0 models.AdminCapabilities
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.UserRole) (models.AdminCapabilities, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.UserRole) models.AdminCapabilities); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Get(0).(models.AdminCapabilities)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.UserRole) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type AdminService_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
//   - ctx context.Context
//   - role models.UserRole
func (_e *AdminService_Expecter) GetCapabilities(ctx interface{}, role interface{}) *AdminService_GetCapabilities_Call {
	return &AdminService_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities", ctx, role)}
}

func (_c *AdminService_GetCapabilities_Call) Run(run func(ctx context.Context, role models.UserRole)) *AdminService_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.UserRole))
	})
	return _c
}

func (_c *AdminService_GetCapabilities_Call) Return(_a0 models.AdminCapabilities, _a1 error) *AdminService_GetCapabilities_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_GetCapabilities_Call) RunAndReturn(run func(context.Context, models.UserRole) (models.AdminCapabilities, error)) *AdminService_GetCapabilities_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, userID
func (_m *AdminService) GetUser(ctx context.Context, userID uuid.UUID) (models.AdminUser, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.AdminUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (models.AdminUser, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) models.AdminUser); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.AdminUser)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type AdminService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AdminService_Expecter) GetUser(ctx interface{}, userID interface{}) *AdminService_GetUser_Call {
	return &AdminService_GetUser_Call{Call: _e.mock.On("GetUser", ctx, userID)}
}

func (_c *AdminService_GetUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AdminService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *AdminService_GetUser_Call) Return(_a0 models.AdminUser, _a1 error) *AdminService_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_GetUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (models.AdminUser, error)) *AdminService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserSessions provides a mock function with given fields: ctx, actorUserID, targetUserID
func (_m *AdminService) ListUserSessions(ctx context.Context, actorUserID uuid.UUID, targetUserID uuid.UUID) ([]models.AdminUserSession, error) {
	ret := _m.Called(ctx, actorUserID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserSessions")
	}

	var r0 []models.AdminUserSession
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]models.AdminUserSession, error)); ok {
		return rf(ctx, actorUserID, targetUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []models.AdminUserSession); ok {
		r0 = rf(ctx, actorUserID, targetUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AdminUserSession)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, actorUserID, targetUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_ListUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserSessions'
type AdminService_ListUserSessions_Call struct {
	*mock.Call
}

// ListUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - actorUserID uuid.UUID
//   - targetUserID uuid.UUID
func (_e *AdminService_Expecter) ListUserSessions(ctx interface{}, actorUserID interface{}, targetUserID interface{}) *AdminService_ListUserSessions_Call {
	return &AdminService_ListUserSessions_Call{Call: _e.mock.On("ListUserSessions", ctx, actorUserID, targetUserID)}
}

func (_c *AdminService_ListUserSessions_Call) Run(run func(ctx context.Context, actorUserID uuid.UUID, targetUserID uuid.UUID)) *AdminService_ListUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *AdminService_ListUserSessions_Call) Return(_a0 []models.AdminUserSession, _a1 error) *AdminService_ListUserSessions_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_ListUserSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) ([]models.AdminUserSession, error)) *AdminService_ListUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function with given fields: ctx, input
func (_m *AdminService) ListUsers(ctx context.Context, input models.ListAdminUsersInput) (models.ListAdminUsersResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 models.ListAdminUsersResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListAdminUsersInput) (models.ListAdminUsersResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListAdminUsersInput) models.ListAdminUsersResult); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.ListAdminUsersResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListAdminUsersInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type AdminService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.ListAdminUsersInput
func (_e *AdminService_Expecter) ListUsers(ctx interface{}, input interface{}) *AdminService_ListUsers_Call {
	return &AdminService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, input)}
}

func (_c *AdminService_ListUsers_Call) Run(run func(ctx context.Context, input models.ListAdminUsersInput)) *AdminService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.ListAdminUsersInput))
	})
	return _c
}

func (_c *AdminService_ListUsers_Call) Return(_a0 models.ListAdminUsersResult, _a1 error) *AdminService_ListUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_ListUsers_Call) RunAndReturn(run func(context.Context, models.ListAdminUsersInput) (models.ListAdminUsersResult, error)) *AdminService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RecordAudit provides a mock function with given fields: ctx, input
func (_m *AdminService) RecordAudit(ctx context.Context, input models.CreateAdminAuditLogInput) (models.AdminAuditLog, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RecordAudit")
	}

	var r0 models.AdminAuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateAdminAuditLogInput) (models.AdminAuditLog, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.CreateAdminAuditLogInput) models.AdminAuditLog); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Get(0).(models.AdminAuditLog)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.CreateAdminAuditLogInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AdminService_RecordAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordAudit'
type AdminService_RecordAudit_Call struct {
	*mock.Call
}

// RecordAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.CreateAdminAuditLogInput
func (_e *AdminService_Expecter) RecordAudit(ctx interface{}, input interface{}) *AdminService_RecordAudit_Call {
	return &AdminService_RecordAudit_Call{Call: _e.mock.On("RecordAudit", ctx, input)}
}

func (_c *AdminService_RecordAudit_Call) Run(run func(ctx context.Context, input models.CreateAdminAuditLogInput)) *AdminService_RecordAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.CreateAdminAuditLogInput))
	})
	return _c
}

func (_c *AdminService_RecordAudit_Call) Return(_a0 models.AdminAuditLog, _a1 error) *AdminService_RecordAudit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AdminService_RecordAudit_Call) RunAndReturn(run func(context.Context, models.CreateAdminAuditLogInput) (models.AdminAuditLog, error)) *AdminService_RecordAudit_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllUserSessions provides a mock function with given fields: ctx, input
func (_m *AdminService) RevokeAllUserSessions(ctx context.Context, input models.AdminSessionMutationInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllUserSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminSessionMutationInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminService_RevokeAllUserSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllUserSessions'
type AdminService_RevokeAllUserSessions_Call struct {
	*mock.Call
}

// RevokeAllUserSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AdminSessionMutationInput
func (_e *AdminService_Expecter) RevokeAllUserSessions(ctx interface{}, input interface{}) *AdminService_RevokeAllUserSessions_Call {
	return &AdminService_RevokeAllUserSessions_Call{Call: _e.mock.On("RevokeAllUserSessions", ctx, input)}
}

func (_c *AdminService_RevokeAllUserSessions_Call) Run(run func(ctx context.Context, input models.AdminSessionMutationInput)) *AdminService_RevokeAllUserSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AdminSessionMutationInput))
	})
	return _c
}

func (_c *AdminService_RevokeAllUserSessions_Call) Return(_a0 error) *AdminService_RevokeAllUserSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminService_RevokeAllUserSessions_Call) RunAndReturn(run func(context.Context, models.AdminSessionMutationInput) error) *AdminService_RevokeAllUserSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeUserSession provides a mock function with given fields: ctx, input
func (_m *AdminService) RevokeUserSession(ctx context.Context, input models.AdminSessionMutationInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RevokeUserSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.AdminSessionMutationInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminService_RevokeUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeUserSession'
type AdminService_RevokeUserSession_Call struct {
	*mock.Call
}

// RevokeUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - input models.AdminSessionMutationInput
func (_e *AdminService_Expecter) RevokeUserSession(ctx interface{}, input interface{}) *AdminService_RevokeUserSession_Call {
	return &AdminService_RevokeUserSession_Call{Call: _e.mock.On("RevokeUserSession", ctx, input)}
}

func (_c *AdminService_RevokeUserSession_Call) Run(run func(ctx context.Context, input models.AdminSessionMutationInput)) *AdminService_RevokeUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.AdminSessionMutationInput))
	})
	return _c
}

func (_c *AdminService_RevokeUserSession_Call) Return(_a0 error) *AdminService_RevokeUserSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AdminService_RevokeUserSession_Call) RunAndReturn(run func(context.Context, models.AdminSessionMutationInput) error) *AdminService_RevokeUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
