// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DurationDetector is an autogenerated mock type for the DurationDetector type
type DurationDetector struct {
	mock.Mock
}

type DurationDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *DurationDetector) EXPECT() *DurationDetector_Expecter {
	return &DurationDetector_Expecter{mock: &_m.Mock}
}

// DetectDuration provides a mock function with given fields: ctx, path
func (_m *DurationDetector) DetectDuration(ctx context.Context, path string) (int, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DetectDuration")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DurationDetector_DetectDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectDuration'
type DurationDetector_DetectDuration_Call struct {
	*mock.Call
}

// DetectDuration is a helper method to define mock.On call
//   - ctx context.Context
//   - path string
func (_e *DurationDetector_Expecter) DetectDuration(ctx interface{}, path interface{}) *DurationDetector_DetectDuration_Call {
	return &DurationDetector_DetectDuration_Call{Call: _e.mock.On("DetectDuration", ctx, path)}
}

func (_c *DurationDetector_DetectDuration_Call) Run(run func(ctx context.Context, path string)) *DurationDetector_DetectDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DurationDetector_DetectDuration_Call) Return(_a0 int, _a1 error) *DurationDetector_DetectDuration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DurationDetector_DetectDuration_Call) RunAndReturn(run func(context.Context, string) (int, error)) *DurationDetector_DetectDuration_Call {
	_c.Call.Return(run)
	return _c
}

// NewDurationDetector creates a new instance of DurationDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDurationDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *DurationDetector {
	mock := &DurationDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
