// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// BillingLimiter is an autogenerated mock type for the BillingLimiter type
type BillingLimiter struct {
	mock.Mock
}

type BillingLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *BillingLimiter) EXPECT() *BillingLimiter_Expecter {
	return &BillingLimiter_Expecter{mock: &_m.Mock}
}

// AddBusinessUsageMinutes provides a mock function with given fields: ctx, companyID, durationSeconds
func (_m *BillingLimiter) AddBusinessUsageMinutes(ctx context.Context, companyID uuid.UUID, durationSeconds int) error {
	ret := _m.Called(ctx, companyID, durationSeconds)

	if len(ret) == 0 {
		panic("no return value specified for AddBusinessUsageMinutes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, companyID, durationSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_AddBusinessUsageMinutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBusinessUsageMinutes'
type BillingLimiter_AddBusinessUsageMinutes_Call struct {
	*mock.Call
}

// AddBusinessUsageMinutes is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - durationSeconds int
func (_e *BillingLimiter_Expecter) AddBusinessUsageMinutes(ctx interface{}, companyID interface{}, durationSeconds interface{}) *BillingLimiter_AddBusinessUsageMinutes_Call {
	return &BillingLimiter_AddBusinessUsageMinutes_Call{Call: _e.mock.On("AddBusinessUsageMinutes", ctx, companyID, durationSeconds)}
}

func (_c *BillingLimiter_AddBusinessUsageMinutes_Call) Run(run func(ctx context.Context, companyID uuid.UUID, durationSeconds int)) *BillingLimiter_AddBusinessUsageMinutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *BillingLimiter_AddBusinessUsageMinutes_Call) Return(_a0 error) *BillingLimiter_AddBusinessUsageMinutes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_AddBusinessUsageMinutes_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *BillingLimiter_AddBusinessUsageMinutes_Call {
	_c.Call.Return(run)
	return _c
}

// AddPersonalUsageMinutes provides a mock function with given fields: ctx, userID, durationSeconds
func (_m *BillingLimiter) AddPersonalUsageMinutes(ctx context.Context, userID uuid.UUID, durationSeconds int) error {
	ret := _m.Called(ctx, userID, durationSeconds)

	if len(ret) == 0 {
		panic("no return value specified for AddPersonalUsageMinutes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, durationSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_AddPersonalUsageMinutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPersonalUsageMinutes'
type BillingLimiter_AddPersonalUsageMinutes_Call struct {
	*mock.Call
}

// AddPersonalUsageMinutes is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - durationSeconds int
func (_e *BillingLimiter_Expecter) AddPersonalUsageMinutes(ctx interface{}, userID interface{}, durationSeconds interface{}) *BillingLimiter_AddPersonalUsageMinutes_Call {
	return &BillingLimiter_AddPersonalUsageMinutes_Call{Call: _e.mock.On("AddPersonalUsageMinutes", ctx, userID, durationSeconds)}
}

func (_c *BillingLimiter_AddPersonalUsageMinutes_Call) Run(run func(ctx context.Context, userID uuid.UUID, durationSeconds int)) *BillingLimiter_AddPersonalUsageMinutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *BillingLimiter_AddPersonalUsageMinutes_Call) Return(_a0 error) *BillingLimiter_AddPersonalUsageMinutes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_AddPersonalUsageMinutes_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *BillingLimiter_AddPersonalUsageMinutes_Call {
	_c.Call.Return(run)
	return _c
}

// CanUploadBusinessCall provides a mock function with given fields: ctx, companyID, durationSeconds
func (_m *BillingLimiter) CanUploadBusinessCall(ctx context.Context, companyID uuid.UUID, durationSeconds int) error {
	ret := _m.Called(ctx, companyID, durationSeconds)

	if len(ret) == 0 {
		panic("no return value specified for CanUploadBusinessCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, companyID, durationSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanUploadBusinessCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUploadBusinessCall'
type BillingLimiter_CanUploadBusinessCall_Call struct {
	*mock.Call
}

// CanUploadBusinessCall is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - durationSeconds int
func (_e *BillingLimiter_Expecter) CanUploadBusinessCall(ctx interface{}, companyID interface{}, durationSeconds interface{}) *BillingLimiter_CanUploadBusinessCall_Call {
	return &BillingLimiter_CanUploadBusinessCall_Call{Call: _e.mock.On("CanUploadBusinessCall", ctx, companyID, durationSeconds)}
}

func (_c *BillingLimiter_CanUploadBusinessCall_Call) Run(run func(ctx context.Context, companyID uuid.UUID, durationSeconds int)) *BillingLimiter_CanUploadBusinessCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *BillingLimiter_CanUploadBusinessCall_Call) Return(_a0 error) *BillingLimiter_CanUploadBusinessCall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanUploadBusinessCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *BillingLimiter_CanUploadBusinessCall_Call {
	_c.Call.Return(run)
	return _c
}

// CanUploadPersonalCall provides a mock function with given fields: ctx, userID, durationSeconds
func (_m *BillingLimiter) CanUploadPersonalCall(ctx context.Context, userID uuid.UUID, durationSeconds int) error {
	ret := _m.Called(ctx, userID, durationSeconds)

	if len(ret) == 0 {
		panic("no return value specified for CanUploadPersonalCall")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) error); ok {
		r0 = rf(ctx, userID, durationSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanUploadPersonalCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanUploadPersonalCall'
type BillingLimiter_CanUploadPersonalCall_Call struct {
	*mock.Call
}

// CanUploadPersonalCall is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - durationSeconds int
func (_e *BillingLimiter_Expecter) CanUploadPersonalCall(ctx interface{}, userID interface{}, durationSeconds interface{}) *BillingLimiter_CanUploadPersonalCall_Call {
	return &BillingLimiter_CanUploadPersonalCall_Call{Call: _e.mock.On("CanUploadPersonalCall", ctx, userID, durationSeconds)}
}

func (_c *BillingLimiter_CanUploadPersonalCall_Call) Run(run func(ctx context.Context, userID uuid.UUID, durationSeconds int)) *BillingLimiter_CanUploadPersonalCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int))
	})
	return _c
}

func (_c *BillingLimiter_CanUploadPersonalCall_Call) Return(_a0 error) *BillingLimiter_CanUploadPersonalCall_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanUploadPersonalCall_Call) RunAndReturn(run func(context.Context, uuid.UUID, int) error) *BillingLimiter_CanUploadPersonalCall_Call {
	_c.Call.Return(run)
	return _c
}

// NewBillingLimiter creates a new instance of BillingLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingLimiter {
	mock := &BillingLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
