// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// BillingLimiter is an autogenerated mock type for the BillingLimiter type
type BillingLimiter struct {
	mock.Mock
}

type BillingLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *BillingLimiter) EXPECT() *BillingLimiter_Expecter {
	return &BillingLimiter_Expecter{mock: &_m.Mock}
}

// CanCreateCompanyInstruction provides a mock function with given fields: ctx, companyID
func (_m *BillingLimiter) CanCreateCompanyInstruction(ctx context.Context, companyID uuid.UUID) error {
	ret := _m.Called(ctx, companyID)

	if len(ret) == 0 {
		panic("no return value specified for CanCreateCompanyInstruction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanCreateCompanyInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanCreateCompanyInstruction'
type BillingLimiter_CanCreateCompanyInstruction_Call struct {
	*mock.Call
}

// CanCreateCompanyInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
func (_e *BillingLimiter_Expecter) CanCreateCompanyInstruction(ctx interface{}, companyID interface{}) *BillingLimiter_CanCreateCompanyInstruction_Call {
	return &BillingLimiter_CanCreateCompanyInstruction_Call{Call: _e.mock.On("CanCreateCompanyInstruction", ctx, companyID)}
}

func (_c *BillingLimiter_CanCreateCompanyInstruction_Call) Run(run func(ctx context.Context, companyID uuid.UUID)) *BillingLimiter_CanCreateCompanyInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_CanCreateCompanyInstruction_Call) Return(_a0 error) *BillingLimiter_CanCreateCompanyInstruction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanCreateCompanyInstruction_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *BillingLimiter_CanCreateCompanyInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// CanCreateDepartmentInstruction provides a mock function with given fields: ctx, companyID, departmentID
func (_m *BillingLimiter) CanCreateDepartmentInstruction(ctx context.Context, companyID uuid.UUID, departmentID uuid.UUID) error {
	ret := _m.Called(ctx, companyID, departmentID)

	if len(ret) == 0 {
		panic("no return value specified for CanCreateDepartmentInstruction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, companyID, departmentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanCreateDepartmentInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanCreateDepartmentInstruction'
type BillingLimiter_CanCreateDepartmentInstruction_Call struct {
	*mock.Call
}

// CanCreateDepartmentInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - companyID uuid.UUID
//   - departmentID uuid.UUID
func (_e *BillingLimiter_Expecter) CanCreateDepartmentInstruction(ctx interface{}, companyID interface{}, departmentID interface{}) *BillingLimiter_CanCreateDepartmentInstruction_Call {
	return &BillingLimiter_CanCreateDepartmentInstruction_Call{Call: _e.mock.On("CanCreateDepartmentInstruction", ctx, companyID, departmentID)}
}

func (_c *BillingLimiter_CanCreateDepartmentInstruction_Call) Run(run func(ctx context.Context, companyID uuid.UUID, departmentID uuid.UUID)) *BillingLimiter_CanCreateDepartmentInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_CanCreateDepartmentInstruction_Call) Return(_a0 error) *BillingLimiter_CanCreateDepartmentInstruction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanCreateDepartmentInstruction_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *BillingLimiter_CanCreateDepartmentInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// CanCreatePersonalInstruction provides a mock function with given fields: ctx, userID
func (_m *BillingLimiter) CanCreatePersonalInstruction(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CanCreatePersonalInstruction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BillingLimiter_CanCreatePersonalInstruction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanCreatePersonalInstruction'
type BillingLimiter_CanCreatePersonalInstruction_Call struct {
	*mock.Call
}

// CanCreatePersonalInstruction is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *BillingLimiter_Expecter) CanCreatePersonalInstruction(ctx interface{}, userID interface{}) *BillingLimiter_CanCreatePersonalInstruction_Call {
	return &BillingLimiter_CanCreatePersonalInstruction_Call{Call: _e.mock.On("CanCreatePersonalInstruction", ctx, userID)}
}

func (_c *BillingLimiter_CanCreatePersonalInstruction_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *BillingLimiter_CanCreatePersonalInstruction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *BillingLimiter_CanCreatePersonalInstruction_Call) Return(_a0 error) *BillingLimiter_CanCreatePersonalInstruction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *BillingLimiter_CanCreatePersonalInstruction_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *BillingLimiter_CanCreatePersonalInstruction_Call {
	_c.Call.Return(run)
	return _c
}

// NewBillingLimiter creates a new instance of BillingLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingLimiter {
	mock := &BillingLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
