with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: false
issue-845-fix: true

packages:
  "calllens/monolit/internal/repository":
    config:
      include-regex: ".*Repository"
  "calllens/monolit/internal/service":
    config:
      include-regex: ".*Service"
  "calllens/monolit/internal/storage":
    config:
      include-regex: "Storage"
