// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AnalyticsAPI is an autogenerated mock type for the AnalyticsAPI type
type AnalyticsAPI struct {
	mock.Mock
}

type AnalyticsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AnalyticsAPI) EXPECT() *AnalyticsAPI_Expecter {
	return &AnalyticsAPI_Expecter{mock: &_m.Mock}
}

// CreateAggregateReport provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) CreateAggregateReport(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_CreateAggregateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAggregateReport'
type AnalyticsAPI_CreateAggregateReport_Call struct {
	*mock.Call
}

// CreateAggregateReport is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) CreateAggregateReport(w interface{}, r interface{}) *AnalyticsAPI_CreateAggregateReport_Call {
	return &AnalyticsAPI_CreateAggregateReport_Call{Call: _e.mock.On("CreateAggregateReport", w, r)}
}

func (_c *AnalyticsAPI_CreateAggregateReport_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_CreateAggregateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_CreateAggregateReport_Call) Return() *AnalyticsAPI_CreateAggregateReport_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_CreateAggregateReport_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_CreateAggregateReport_Call {
	_c.Run(run)
	return _c
}

// CreateDeepAnalysis provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) CreateDeepAnalysis(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_CreateDeepAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeepAnalysis'
type AnalyticsAPI_CreateDeepAnalysis_Call struct {
	*mock.Call
}

// CreateDeepAnalysis is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) CreateDeepAnalysis(w interface{}, r interface{}) *AnalyticsAPI_CreateDeepAnalysis_Call {
	return &AnalyticsAPI_CreateDeepAnalysis_Call{Call: _e.mock.On("CreateDeepAnalysis", w, r)}
}

func (_c *AnalyticsAPI_CreateDeepAnalysis_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_CreateDeepAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_CreateDeepAnalysis_Call) Return() *AnalyticsAPI_CreateDeepAnalysis_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_CreateDeepAnalysis_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_CreateDeepAnalysis_Call {
	_c.Run(run)
	return _c
}

// DeepAnalysisEvents provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) DeepAnalysisEvents(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_DeepAnalysisEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeepAnalysisEvents'
type AnalyticsAPI_DeepAnalysisEvents_Call struct {
	*mock.Call
}

// DeepAnalysisEvents is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) DeepAnalysisEvents(w interface{}, r interface{}) *AnalyticsAPI_DeepAnalysisEvents_Call {
	return &AnalyticsAPI_DeepAnalysisEvents_Call{Call: _e.mock.On("DeepAnalysisEvents", w, r)}
}

func (_c *AnalyticsAPI_DeepAnalysisEvents_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_DeepAnalysisEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_DeepAnalysisEvents_Call) Return() *AnalyticsAPI_DeepAnalysisEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_DeepAnalysisEvents_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_DeepAnalysisEvents_Call {
	_c.Run(run)
	return _c
}

// DeleteAggregateReport provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) DeleteAggregateReport(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_DeleteAggregateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAggregateReport'
type AnalyticsAPI_DeleteAggregateReport_Call struct {
	*mock.Call
}

// DeleteAggregateReport is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) DeleteAggregateReport(w interface{}, r interface{}) *AnalyticsAPI_DeleteAggregateReport_Call {
	return &AnalyticsAPI_DeleteAggregateReport_Call{Call: _e.mock.On("DeleteAggregateReport", w, r)}
}

func (_c *AnalyticsAPI_DeleteAggregateReport_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_DeleteAggregateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_DeleteAggregateReport_Call) Return() *AnalyticsAPI_DeleteAggregateReport_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_DeleteAggregateReport_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_DeleteAggregateReport_Call {
	_c.Run(run)
	return _c
}

// DownloadAggregateReport provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) DownloadAggregateReport(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_DownloadAggregateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAggregateReport'
type AnalyticsAPI_DownloadAggregateReport_Call struct {
	*mock.Call
}

// DownloadAggregateReport is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) DownloadAggregateReport(w interface{}, r interface{}) *AnalyticsAPI_DownloadAggregateReport_Call {
	return &AnalyticsAPI_DownloadAggregateReport_Call{Call: _e.mock.On("DownloadAggregateReport", w, r)}
}

func (_c *AnalyticsAPI_DownloadAggregateReport_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_DownloadAggregateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_DownloadAggregateReport_Call) Return() *AnalyticsAPI_DownloadAggregateReport_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_DownloadAggregateReport_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_DownloadAggregateReport_Call {
	_c.Run(run)
	return _c
}

// GetDeepAnalysis provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) GetDeepAnalysis(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_GetDeepAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeepAnalysis'
type AnalyticsAPI_GetDeepAnalysis_Call struct {
	*mock.Call
}

// GetDeepAnalysis is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) GetDeepAnalysis(w interface{}, r interface{}) *AnalyticsAPI_GetDeepAnalysis_Call {
	return &AnalyticsAPI_GetDeepAnalysis_Call{Call: _e.mock.On("GetDeepAnalysis", w, r)}
}

func (_c *AnalyticsAPI_GetDeepAnalysis_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_GetDeepAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_GetDeepAnalysis_Call) Return() *AnalyticsAPI_GetDeepAnalysis_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_GetDeepAnalysis_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_GetDeepAnalysis_Call {
	_c.Run(run)
	return _c
}

// GetOverview provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) GetOverview(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_GetOverview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOverview'
type AnalyticsAPI_GetOverview_Call struct {
	*mock.Call
}

// GetOverview is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) GetOverview(w interface{}, r interface{}) *AnalyticsAPI_GetOverview_Call {
	return &AnalyticsAPI_GetOverview_Call{Call: _e.mock.On("GetOverview", w, r)}
}

func (_c *AnalyticsAPI_GetOverview_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_GetOverview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_GetOverview_Call) Return() *AnalyticsAPI_GetOverview_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_GetOverview_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_GetOverview_Call {
	_c.Run(run)
	return _c
}

// ListAggregateReports provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) ListAggregateReports(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_ListAggregateReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAggregateReports'
type AnalyticsAPI_ListAggregateReports_Call struct {
	*mock.Call
}

// ListAggregateReports is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) ListAggregateReports(w interface{}, r interface{}) *AnalyticsAPI_ListAggregateReports_Call {
	return &AnalyticsAPI_ListAggregateReports_Call{Call: _e.mock.On("ListAggregateReports", w, r)}
}

func (_c *AnalyticsAPI_ListAggregateReports_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_ListAggregateReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_ListAggregateReports_Call) Return() *AnalyticsAPI_ListAggregateReports_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_ListAggregateReports_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_ListAggregateReports_Call {
	_c.Run(run)
	return _c
}

// ListDeepAnalyses provides a mock function with given fields: w, r
func (_m *AnalyticsAPI) ListDeepAnalyses(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AnalyticsAPI_ListDeepAnalyses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeepAnalyses'
type AnalyticsAPI_ListDeepAnalyses_Call struct {
	*mock.Call
}

// ListDeepAnalyses is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AnalyticsAPI_Expecter) ListDeepAnalyses(w interface{}, r interface{}) *AnalyticsAPI_ListDeepAnalyses_Call {
	return &AnalyticsAPI_ListDeepAnalyses_Call{Call: _e.mock.On("ListDeepAnalyses", w, r)}
}

func (_c *AnalyticsAPI_ListDeepAnalyses_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AnalyticsAPI_ListDeepAnalyses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AnalyticsAPI_ListDeepAnalyses_Call) Return() *AnalyticsAPI_ListDeepAnalyses_Call {
	_c.Call.Return()
	return _c
}

func (_c *AnalyticsAPI_ListDeepAnalyses_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AnalyticsAPI_ListDeepAnalyses_Call {
	_c.Run(run)
	return _c
}

// NewAnalyticsAPI creates a new instance of AnalyticsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAnalyticsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsAPI {
	mock := &AnalyticsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
