// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

type AnalyticsAPI struct {
	mock.Mock
}

func (_m *AnalyticsAPI) GetOverview(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

func NewAnalyticsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AnalyticsAPI {
	mock := &AnalyticsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
