// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// DepartmentAPI is an autogenerated mock type for the DepartmentAPI type
type DepartmentAPI struct {
	mock.Mock
}

type DepartmentAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *DepartmentAPI) EXPECT() *DepartmentAPI_Expecter {
	return &DepartmentAPI_Expecter{mock: &_m.Mock}
}

// AddDepartmentMember provides a mock function with given fields: w, r
func (_m *DepartmentAPI) AddDepartmentMember(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_AddDepartmentMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddDepartmentMember'
type DepartmentAPI_AddDepartmentMember_Call struct {
	*mock.Call
}

// AddDepartmentMember is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) AddDepartmentMember(w interface{}, r interface{}) *DepartmentAPI_AddDepartmentMember_Call {
	return &DepartmentAPI_AddDepartmentMember_Call{Call: _e.mock.On("AddDepartmentMember", w, r)}
}

func (_c *DepartmentAPI_AddDepartmentMember_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_AddDepartmentMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_AddDepartmentMember_Call) Return() *DepartmentAPI_AddDepartmentMember_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_AddDepartmentMember_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_AddDepartmentMember_Call {
	_c.Run(run)
	return _c
}

// CreateDepartment provides a mock function with given fields: w, r
func (_m *DepartmentAPI) CreateDepartment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_CreateDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDepartment'
type DepartmentAPI_CreateDepartment_Call struct {
	*mock.Call
}

// CreateDepartment is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) CreateDepartment(w interface{}, r interface{}) *DepartmentAPI_CreateDepartment_Call {
	return &DepartmentAPI_CreateDepartment_Call{Call: _e.mock.On("CreateDepartment", w, r)}
}

func (_c *DepartmentAPI_CreateDepartment_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_CreateDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_CreateDepartment_Call) Return() *DepartmentAPI_CreateDepartment_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_CreateDepartment_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_CreateDepartment_Call {
	_c.Run(run)
	return _c
}

// DeleteDepartment provides a mock function with given fields: w, r
func (_m *DepartmentAPI) DeleteDepartment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_DeleteDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDepartment'
type DepartmentAPI_DeleteDepartment_Call struct {
	*mock.Call
}

// DeleteDepartment is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) DeleteDepartment(w interface{}, r interface{}) *DepartmentAPI_DeleteDepartment_Call {
	return &DepartmentAPI_DeleteDepartment_Call{Call: _e.mock.On("DeleteDepartment", w, r)}
}

func (_c *DepartmentAPI_DeleteDepartment_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_DeleteDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_DeleteDepartment_Call) Return() *DepartmentAPI_DeleteDepartment_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_DeleteDepartment_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_DeleteDepartment_Call {
	_c.Run(run)
	return _c
}

// ListDepartmentMembers provides a mock function with given fields: w, r
func (_m *DepartmentAPI) ListDepartmentMembers(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_ListDepartmentMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDepartmentMembers'
type DepartmentAPI_ListDepartmentMembers_Call struct {
	*mock.Call
}

// ListDepartmentMembers is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) ListDepartmentMembers(w interface{}, r interface{}) *DepartmentAPI_ListDepartmentMembers_Call {
	return &DepartmentAPI_ListDepartmentMembers_Call{Call: _e.mock.On("ListDepartmentMembers", w, r)}
}

func (_c *DepartmentAPI_ListDepartmentMembers_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_ListDepartmentMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_ListDepartmentMembers_Call) Return() *DepartmentAPI_ListDepartmentMembers_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_ListDepartmentMembers_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_ListDepartmentMembers_Call {
	_c.Run(run)
	return _c
}

// ListDepartments provides a mock function with given fields: w, r
func (_m *DepartmentAPI) ListDepartments(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_ListDepartments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDepartments'
type DepartmentAPI_ListDepartments_Call struct {
	*mock.Call
}

// ListDepartments is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) ListDepartments(w interface{}, r interface{}) *DepartmentAPI_ListDepartments_Call {
	return &DepartmentAPI_ListDepartments_Call{Call: _e.mock.On("ListDepartments", w, r)}
}

func (_c *DepartmentAPI_ListDepartments_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_ListDepartments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_ListDepartments_Call) Return() *DepartmentAPI_ListDepartments_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_ListDepartments_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_ListDepartments_Call {
	_c.Run(run)
	return _c
}

// UpdateDepartment provides a mock function with given fields: w, r
func (_m *DepartmentAPI) UpdateDepartment(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_UpdateDepartment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartment'
type DepartmentAPI_UpdateDepartment_Call struct {
	*mock.Call
}

// UpdateDepartment is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) UpdateDepartment(w interface{}, r interface{}) *DepartmentAPI_UpdateDepartment_Call {
	return &DepartmentAPI_UpdateDepartment_Call{Call: _e.mock.On("UpdateDepartment", w, r)}
}

func (_c *DepartmentAPI_UpdateDepartment_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_UpdateDepartment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_UpdateDepartment_Call) Return() *DepartmentAPI_UpdateDepartment_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_UpdateDepartment_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_UpdateDepartment_Call {
	_c.Run(run)
	return _c
}

// UpdateDepartmentMemberRole provides a mock function with given fields: w, r
func (_m *DepartmentAPI) UpdateDepartmentMemberRole(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_UpdateDepartmentMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartmentMemberRole'
type DepartmentAPI_UpdateDepartmentMemberRole_Call struct {
	*mock.Call
}

// UpdateDepartmentMemberRole is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) UpdateDepartmentMemberRole(w interface{}, r interface{}) *DepartmentAPI_UpdateDepartmentMemberRole_Call {
	return &DepartmentAPI_UpdateDepartmentMemberRole_Call{Call: _e.mock.On("UpdateDepartmentMemberRole", w, r)}
}

func (_c *DepartmentAPI_UpdateDepartmentMemberRole_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_UpdateDepartmentMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_UpdateDepartmentMemberRole_Call) Return() *DepartmentAPI_UpdateDepartmentMemberRole_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_UpdateDepartmentMemberRole_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_UpdateDepartmentMemberRole_Call {
	_c.Run(run)
	return _c
}

// UpdateDepartmentMemberStatus provides a mock function with given fields: w, r
func (_m *DepartmentAPI) UpdateDepartmentMemberStatus(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// DepartmentAPI_UpdateDepartmentMemberStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDepartmentMemberStatus'
type DepartmentAPI_UpdateDepartmentMemberStatus_Call struct {
	*mock.Call
}

// UpdateDepartmentMemberStatus is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *DepartmentAPI_Expecter) UpdateDepartmentMemberStatus(w interface{}, r interface{}) *DepartmentAPI_UpdateDepartmentMemberStatus_Call {
	return &DepartmentAPI_UpdateDepartmentMemberStatus_Call{Call: _e.mock.On("UpdateDepartmentMemberStatus", w, r)}
}

func (_c *DepartmentAPI_UpdateDepartmentMemberStatus_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *DepartmentAPI_UpdateDepartmentMemberStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *DepartmentAPI_UpdateDepartmentMemberStatus_Call) Return() *DepartmentAPI_UpdateDepartmentMemberStatus_Call {
	_c.Call.Return()
	return _c
}

func (_c *DepartmentAPI_UpdateDepartmentMemberStatus_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *DepartmentAPI_UpdateDepartmentMemberStatus_Call {
	_c.Run(run)
	return _c
}

// NewDepartmentAPI creates a new instance of DepartmentAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepartmentAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepartmentAPI {
	mock := &DepartmentAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
