// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AuthAPI is an autogenerated mock type for the AuthAPI type
type AuthAPI struct {
	mock.Mock
}

type AuthAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthAPI) EXPECT() *AuthAPI_Expecter {
	return &AuthAPI_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: w, r
func (_m *AuthAPI) Login(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthAPI_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) Login(w interface{}, r interface{}) *AuthAPI_Login_Call {
	return &AuthAPI_Login_Call{Call: _e.mock.On("Login", w, r)}
}

func (_c *AuthAPI_Login_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_Login_Call) Return() *AuthAPI_Login_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_Login_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_Login_Call {
	_c.Run(run)
	return _c
}

// Logout provides a mock function with given fields: w, r
func (_m *AuthAPI) Logout(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthAPI_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) Logout(w interface{}, r interface{}) *AuthAPI_Logout_Call {
	return &AuthAPI_Logout_Call{Call: _e.mock.On("Logout", w, r)}
}

func (_c *AuthAPI_Logout_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_Logout_Call) Return() *AuthAPI_Logout_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_Logout_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_Logout_Call {
	_c.Run(run)
	return _c
}

// LogoutAll provides a mock function with given fields: w, r
func (_m *AuthAPI) LogoutAll(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type AuthAPI_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) LogoutAll(w interface{}, r interface{}) *AuthAPI_LogoutAll_Call {
	return &AuthAPI_LogoutAll_Call{Call: _e.mock.On("LogoutAll", w, r)}
}

func (_c *AuthAPI_LogoutAll_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_LogoutAll_Call) Return() *AuthAPI_LogoutAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_LogoutAll_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_LogoutAll_Call {
	_c.Run(run)
	return _c
}

// LookupUser provides a mock function with given fields: w, r
func (_m *AuthAPI) LookupUser(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_LookupUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupUser'
type AuthAPI_LookupUser_Call struct {
	*mock.Call
}

// LookupUser is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) LookupUser(w interface{}, r interface{}) *AuthAPI_LookupUser_Call {
	return &AuthAPI_LookupUser_Call{Call: _e.mock.On("LookupUser", w, r)}
}

func (_c *AuthAPI_LookupUser_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_LookupUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_LookupUser_Call) Return() *AuthAPI_LookupUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_LookupUser_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_LookupUser_Call {
	_c.Run(run)
	return _c
}

// Me provides a mock function with given fields: w, r
func (_m *AuthAPI) Me(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type AuthAPI_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) Me(w interface{}, r interface{}) *AuthAPI_Me_Call {
	return &AuthAPI_Me_Call{Call: _e.mock.On("Me", w, r)}
}

func (_c *AuthAPI_Me_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_Me_Call) Return() *AuthAPI_Me_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_Me_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_Me_Call {
	_c.Run(run)
	return _c
}

// Refresh provides a mock function with given fields: w, r
func (_m *AuthAPI) Refresh(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthAPI_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) Refresh(w interface{}, r interface{}) *AuthAPI_Refresh_Call {
	return &AuthAPI_Refresh_Call{Call: _e.mock.On("Refresh", w, r)}
}

func (_c *AuthAPI_Refresh_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_Refresh_Call) Return() *AuthAPI_Refresh_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_Refresh_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_Refresh_Call {
	_c.Run(run)
	return _c
}

// Register provides a mock function with given fields: w, r
func (_m *AuthAPI) Register(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthAPI_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) Register(w interface{}, r interface{}) *AuthAPI_Register_Call {
	return &AuthAPI_Register_Call{Call: _e.mock.On("Register", w, r)}
}

func (_c *AuthAPI_Register_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_Register_Call) Return() *AuthAPI_Register_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_Register_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_Register_Call {
	_c.Run(run)
	return _c
}

// UpdateUsername provides a mock function with given fields: w, r
func (_m *AuthAPI) UpdateUsername(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AuthAPI_UpdateUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUsername'
type AuthAPI_UpdateUsername_Call struct {
	*mock.Call
}

// UpdateUsername is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AuthAPI_Expecter) UpdateUsername(w interface{}, r interface{}) *AuthAPI_UpdateUsername_Call {
	return &AuthAPI_UpdateUsername_Call{Call: _e.mock.On("UpdateUsername", w, r)}
}

func (_c *AuthAPI_UpdateUsername_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AuthAPI_UpdateUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AuthAPI_UpdateUsername_Call) Return() *AuthAPI_UpdateUsername_Call {
	_c.Call.Return()
	return _c
}

func (_c *AuthAPI_UpdateUsername_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AuthAPI_UpdateUsername_Call {
	_c.Run(run)
	return _c
}

// NewAuthAPI creates a new instance of AuthAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthAPI {
	mock := &AuthAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
