// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// SearchAPI is an autogenerated mock type for the SearchAPI type
type SearchAPI struct {
	mock.Mock
}

type SearchAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SearchAPI) EXPECT() *SearchAPI_Expecter {
	return &SearchAPI_Expecter{mock: &_m.Mock}
}

// Search provides a mock function with given fields: w, r
func (_m *SearchAPI) Search(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// SearchAPI_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type SearchAPI_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *SearchAPI_Expecter) Search(w interface{}, r interface{}) *SearchAPI_Search_Call {
	return &SearchAPI_Search_Call{Call: _e.mock.On("Search", w, r)}
}

func (_c *SearchAPI_Search_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *SearchAPI_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *SearchAPI_Search_Call) Return() *SearchAPI_Search_Call {
	_c.Call.Return()
	return _c
}

func (_c *SearchAPI_Search_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *SearchAPI_Search_Call {
	_c.Run(run)
	return _c
}

// NewSearchAPI creates a new instance of SearchAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSearchAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchAPI {
	mock := &SearchAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
