// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ReportAPI is an autogenerated mock type for the ReportAPI type
type ReportAPI struct {
	mock.Mock
}

type ReportAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportAPI) EXPECT() *ReportAPI_Expecter {
	return &ReportAPI_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: w, r
func (_m *ReportAPI) Create(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ReportAPI_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ReportAPI_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ReportAPI_Expecter) Create(w interface{}, r interface{}) *ReportAPI_Create_Call {
	return &ReportAPI_Create_Call{Call: _e.mock.On("Create", w, r)}
}

func (_c *ReportAPI_Create_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ReportAPI_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ReportAPI_Create_Call) Return() *ReportAPI_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportAPI_Create_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ReportAPI_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function with given fields: w, r
func (_m *ReportAPI) Delete(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ReportAPI_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ReportAPI_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ReportAPI_Expecter) Delete(w interface{}, r interface{}) *ReportAPI_Delete_Call {
	return &ReportAPI_Delete_Call{Call: _e.mock.On("Delete", w, r)}
}

func (_c *ReportAPI_Delete_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ReportAPI_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ReportAPI_Delete_Call) Return() *ReportAPI_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportAPI_Delete_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ReportAPI_Delete_Call {
	_c.Run(run)
	return _c
}

// Download provides a mock function with given fields: w, r
func (_m *ReportAPI) Download(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ReportAPI_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type ReportAPI_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ReportAPI_Expecter) Download(w interface{}, r interface{}) *ReportAPI_Download_Call {
	return &ReportAPI_Download_Call{Call: _e.mock.On("Download", w, r)}
}

func (_c *ReportAPI_Download_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ReportAPI_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ReportAPI_Download_Call) Return() *ReportAPI_Download_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportAPI_Download_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ReportAPI_Download_Call {
	_c.Run(run)
	return _c
}

// ListByCallUUID provides a mock function with given fields: w, r
func (_m *ReportAPI) ListByCallUUID(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// ReportAPI_ListByCallUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByCallUUID'
type ReportAPI_ListByCallUUID_Call struct {
	*mock.Call
}

// ListByCallUUID is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ReportAPI_Expecter) ListByCallUUID(w interface{}, r interface{}) *ReportAPI_ListByCallUUID_Call {
	return &ReportAPI_ListByCallUUID_Call{Call: _e.mock.On("ListByCallUUID", w, r)}
}

func (_c *ReportAPI_ListByCallUUID_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ReportAPI_ListByCallUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ReportAPI_ListByCallUUID_Call) Return() *ReportAPI_ListByCallUUID_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportAPI_ListByCallUUID_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *ReportAPI_ListByCallUUID_Call {
	_c.Run(run)
	return _c
}

// NewReportAPI creates a new instance of ReportAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportAPI {
	mock := &ReportAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
