// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MonitoringAPI is an autogenerated mock type for the MonitoringAPI type
type MonitoringAPI struct {
	mock.Mock
}

type MonitoringAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MonitoringAPI) EXPECT() *MonitoringAPI_Expecter {
	return &MonitoringAPI_Expecter{mock: &_m.Mock}
}

// GetProcessing provides a mock function with given fields: w, r
func (_m *MonitoringAPI) GetProcessing(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// MonitoringAPI_GetProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessing'
type MonitoringAPI_GetProcessing_Call struct {
	*mock.Call
}

// GetProcessing is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *MonitoringAPI_Expecter) GetProcessing(w interface{}, r interface{}) *MonitoringAPI_GetProcessing_Call {
	return &MonitoringAPI_GetProcessing_Call{Call: _e.mock.On("GetProcessing", w, r)}
}

func (_c *MonitoringAPI_GetProcessing_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *MonitoringAPI_GetProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *MonitoringAPI_GetProcessing_Call) Return() *MonitoringAPI_GetProcessing_Call {
	_c.Call.Return()
	return _c
}

func (_c *MonitoringAPI_GetProcessing_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *MonitoringAPI_GetProcessing_Call {
	_c.Run(run)
	return _c
}

// NewMonitoringAPI creates a new instance of MonitoringAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMonitoringAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringAPI {
	mock := &MonitoringAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
