// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// AdminAPI is an autogenerated mock type for the AdminAPI type
type AdminAPI struct {
	mock.Mock
}

type AdminAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminAPI) EXPECT() *AdminAPI_Expecter {
	return &AdminAPI_Expecter{mock: &_m.Mock}
}

// GetCapabilities provides a mock function with given fields: w, r
func (_m *AdminAPI) GetCapabilities(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// AdminAPI_GetCapabilities_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCapabilities'
type AdminAPI_GetCapabilities_Call struct {
	*mock.Call
}

// GetCapabilities is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *AdminAPI_Expecter) GetCapabilities(w interface{}, r interface{}) *AdminAPI_GetCapabilities_Call {
	return &AdminAPI_GetCapabilities_Call{Call: _e.mock.On("GetCapabilities", w, r)}
}

func (_c *AdminAPI_GetCapabilities_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *AdminAPI_GetCapabilities_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *AdminAPI_GetCapabilities_Call) Return() *AdminAPI_GetCapabilities_Call {
	_c.Call.Return()
	return _c
}

func (_c *AdminAPI_GetCapabilities_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request)) *AdminAPI_GetCapabilities_Call {
	_c.Run(run)
	return _c
}

// NewAdminAPI creates a new instance of AdminAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminAPI {
	mock := &AdminAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
