// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

type MonitoringAPI struct {
	mock.Mock
}

func (_m *MonitoringAPI) GetProcessing(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

func NewMonitoringAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MonitoringAPI {
	mock := &MonitoringAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
